### ISSUE TITLE
Commands

### ISSUE THREAD

**Issue by amiehx** [fakuivan/TF2-Taunts-TF2IDB#12]
Just installed the plugin on the server i develop, triple checking everything is in its correct place. 

Typed "sm plugins load tf2_taunts_tf2idb" into console, and it continues to say its loaded. But once on the server ingame, i go to test it out, via command, and nothing happens, therefore i went back, checked everything again, still no change.

Really stumped on this now. and seriously started to frustrate me

PLease advise and help

**Comment by fakuivan** [comment]
What Item schema API do you use? What does sm_taunt return? 

The plugin is designed to load even if gamedata is not there/up-to-date to recover by means of the updater. It will (instead of entering fail state) log errors on load if something goes wrong, like seen here https://github.com/fakuivan/TF2-Taunts-TF2IDB/blob/master/scripting/tf2_taunts_tf2idb.sp#L96 . Check the logs and report back.

**Comment by amiehx** [comment]
Using TF2ItemsDB
Apparently Unknown Command, To both Root Flagged and Admin Flagged. Also No Flagged

No Errors seen currently in the logs, Same after many restarts

**Comment by fakuivan** [comment]
What's the output from ``sm plugins info tf2_taunts_tf2idb``?

**Comment by amiehx** [comment]
Filename: tf2_taunts_tf2idb.smx
  Title: TF2 Taunts TF2IDB (An extensible taunt menu that updates along with tf2idb)
  Author: fakuivan
  Version: 1.5.1.47-tf2idb
  URL: https://forums.alliedmods.net/member.php?u=264797
  Error: Required extension "TF2Items" file("tf2items.ext.2.ep2v") not running

**Comment by fakuivan** [comment]
Oh, you don't have TF2Items installed, I forgot to add that step to the installation instructions. Install it and you should be good to go.

**Comment by amiehx** [comment]
Thank you!, will come back if any more problems!
