### ISSUE TITLE
Includes list outdated

### ISSUE THREAD

**Issue by JoinedSenses** [fakuivan/TF2-Taunts-TF2IDB#27]
Requires includes that aren't added to your git

**Comment by fakuivan** [comment]
I don't include other projects in this repo. All includes are downloaded when there's the need to compile the source, [the travis builder does that](https://github.com/fakuivan/TF2-Taunts-TF2IDB/blob/04ae984067114a01489cb820437ebcd9a47ba5ef/.travis.yml#L43-L46) (Yes, I know those should not refernce the master branch, but that's a separate issue).

**Comment by JoinedSenses** [comment]
Right on. I couldn't find those includes anywhere online. I figured they were yours.

**Comment by JoinedSenses** [comment]
Such as 

#include "tf2_taunts_tf2idb/autoversioning.inc"
#include "tf2_taunts_tf2idb/updater_helpers.inc"

**Comment by JoinedSenses** [comment]
Could you at least include information or steps on how to build/compile using travis for folks who've never done it before?

**Comment by fakuivan** [comment]
You're right, you can't find those includes anywhere, they are build dependent. If you wish to make changes to the source and build the project yourself I advice you to read the [.travis.yml](https://github.com/fakuivan/TF2-Taunts-TF2IDB/blob/04ae984067114a01489cb820437ebcd9a47ba5ef/.travis.yml) build file. 
If you just want to compile the latest release from this repo you have two options: 
* Download the latest release file from the [releases](https://github.com/fakuivan/TF2-Taunts-TF2IDB/releases) section. 
* Use the [updater plugins repo](https://github.com/fakuivan/sm_updater_plugins) that hosts files for @GoD-Tony's updater plugin. 

Those have all of the files you need to build the project, then just compile ``tf2_taunts_tf2idb.sp``.
Notes: 
* Add the ``_USE_TF2II_INSTEAD_OF_TF2IDB=`` flag if you plan on building for the TF2II API. 
* You must download the correct package for the correct API, otherwise the updater will update (if you want to build the project for the TF2II API, download that version, and viceversa) you back to the version you downloaded.

**Comment by JoinedSenses** [comment]
Awesome, thank you. I realized how much of a retard I was after realizing there's a /release section. First time I've seen a sourcemod plugin on gh using travis and that section.

**Comment by fakuivan** [comment]
Yes, building this is a PITA, sadly I don't have time for this now, I was thinking I could dedicate some time at the end of the semester. I am still figuring out the best way to build sp projects (maybe [sm-builder](https://github.com/splewis/sm-builder)?), #20 is open for this reason. Thanks for pointing this out. 

Mind changing the title to something more descriptive? Like "Missing autoversioning and updater includes".
