### ISSUE TITLE
Taunt props not visible to players not executing the taunt

### ISSUE THREAD

**Issue by SparklyCatTF2** [fakuivan/TF2-Taunts-TF2IDB#28]
I have the latest version of this plugin running on a windows server, but some taunt items are invisible server side and some aren't. I recorded a clip to show what is happening https://www.youtube.com/watch?v=GYVD754VY2I

**Comment by fakuivan** [comment]
This is a known limitation of fake taunt items. I haven't spent enough time myself to investigate how this could be solved but as far as I know, this is a client-side limitation. 

[The taunt enforcer](https://github.com/fakuivan/TF2-Taunts-TF2IDB/blob/master/scripting/include/tf2_taunts_tf2idb/taunt_enforcer.inc) used by this project is basically a rewrite of @FlaminSarge's [Taunt'em implementation](https://github.com/FlaminSarge/tf_tauntem/blob/master/tf_tauntem.sp#L158-L196), maybe he can shed more light into this issue and how it could be solved. 

About politics: 
Probably the reason why Valve didn't nuke our hacks yet is because they are comfortable with this being 
the (somewhat broken) way it is <sub><sup>(and maybe because of their gambling scandals?)</sup></sub>.

**Comment by ghost** [comment]
Anyone found a fix to this problem?

**Comment by fakuivan** [comment]
There's a fix for it going around the interwebs. I don't think I'll incorporate it into this because valve might get mad and break it.

**Comment by ghost** [comment]
Know of a place where I could find a fix??

**Comment by fakuivan** [comment]
![image](https://user-images.githubusercontent.com/15100012/87710222-d9f77700-c77b-11ea-987a-c0bcd7eae450.png)

Might want to start there @VendMotion

**Comment by FlaminSarge** [comment]
Please tell me it doesn't involve creating a new fake prop entity and timing its visibility based on each specific taunt.

**Comment by ghost** [comment]
No it doesn't. Someone on the Alliedmodders Discord sent me a file with a .sp file to compile that uses a fix to make the taunt props visible to all players on the server.

**Comment by fakuivan** [comment]
> Please tell me it doesn't involve creating a new fake prop entity and timing its visibility based on each specific taunt.

It's literally changing one entity prop

**Comment by madiskoivopuu** [comment]
> No it doesn't. Someone on the Alliedmodders Discord sent me a file with a .sp file to compile that uses a fix to make the taunt props visible to all players on the server.

If its the fix I'm thinking of, then the only time taunt props will disappear is when you tab out of TF2 and go back. Taunting again fixes this issue.

**Comment by gamermonter** [comment]
no have all taunt,what do I do?

**Comment by gamermonter** [comment]
where is the .sp file? for fix that

**Comment by gdfsgdfg** [comment]
this plugin can fix this bug https://github.com/TF2CutContentWiki/TF2ServersidePlayerAttachmentFixer tf2 was rigged so most cosmetics and stuff show up as invisible
